root: "https://melodyevents.nl"
name: "Melodyevents"
description: "Bij Melody Events bent u aan het juiste adress for all uw Trouwfeesten en andere evenementen."

analytics:
  umami_id: ""

metas:
  title: = title
  description: =description
  icon: ""
  lang: en
  generator: true